insert into ingredients (name, ingredient_api_id) values ('balsamic vinegar', 2069);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('mozzarella cheese', 1026);
insert into ingredients (name, ingredient_api_id) values ('red onion', 10011282);
insert into ingredients (name, ingredient_api_id) values ('rosemary', 2036);
insert into ingredients (name, ingredient_api_id) values ('sweet potato', 11507);
insert into ingredients (name, ingredient_api_id) values ('gnocchi', 98853);
insert into ingredients (name, ingredient_api_id) values ('great northern beans', 16025);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('borlotti beans', 10016020);
insert into ingredients (name, ingredient_api_id) values ('carrot', 11124);
insert into ingredients (name, ingredient_api_id) values ('celery stalk', 10111143);
insert into ingredients (name, ingredient_api_id) values ('chile flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('ditalini pasta', 10020499);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('italian seasoning', 1022027);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('tomatoes', 11529);
insert into ingredients (name, ingredient_api_id) values ('vegetable stock', 6615);
insert into ingredients (name, ingredient_api_id) values ('baby spinach', 11457);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('crushed red pepper', 1032009);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('part-skim ricotta cheese', 1037);
insert into ingredients (name, ingredient_api_id) values ('rotini', 11320420);
insert into ingredients (name, ingredient_api_id) values ('white mushrooms', 11260);
insert into ingredients (name, ingredient_api_id) values ('basil leaves', 2044);
insert into ingredients (name, ingredient_api_id) values ('broccoli florets', 10011090);
insert into ingredients (name, ingredient_api_id) values ('cherry tomatoes', 10311529);
insert into ingredients (name, ingredient_api_id) values ('fusilli pasta', 11320420);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('green onions', 11291);
insert into ingredients (name, ingredient_api_id) values ('lemon zest', 9156);
insert into ingredients (name, ingredient_api_id) values ('orange bell pepper', 10011821);
insert into ingredients (name, ingredient_api_id) values ('vegan cheese', 93701);
insert into ingredients (name, ingredient_api_id) values ('yellow squash', 11641);
insert into ingredients (name, ingredient_api_id) values ('almond milk', 93607);
insert into ingredients (name, ingredient_api_id) values ('canned pumpkin', 11424);
insert into ingredients (name, ingredient_api_id) values ('oats', 8120);
insert into ingredients (name, ingredient_api_id) values ('pumpkin pie spice', 1002035);
insert into ingredients (name, ingredient_api_id) values ('baby spinach', 11457);
insert into ingredients (name, ingredient_api_id) values ('cherry tomatoes', 10311529);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('italian turkey sausage', 7927);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('whole-wheat pasta', 20124);
insert into ingredients (name, ingredient_api_id) values ('balsamic vinegar', 2069);
insert into ingredients (name, ingredient_api_id) values ('brown rice', 20040);
insert into ingredients (name, ingredient_api_id) values ('cashews', 12087);
insert into ingredients (name, ingredient_api_id) values ('chives', 11156);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('pine nuts', 12147);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('rosemary', 2036);
insert into ingredients (name, ingredient_api_id) values ('shallots', 11677);
insert into ingredients (name, ingredient_api_id) values ('sweet potato', 11507);
insert into ingredients (name, ingredient_api_id) values ('tomato paste', 11887);
insert into ingredients (name, ingredient_api_id) values ('asparagus spears', 11011);
insert into ingredients (name, ingredient_api_id) values ('canned cannellini beans', 10016051);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('ditalini pasta', 10020499);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('peas', 11304);
insert into ingredients (name, ingredient_api_id) values ('romano cheese', 1038);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('sweet onion', 11294);
insert into ingredients (name, ingredient_api_id) values ('vegetable stock', 6615);
insert into ingredients (name, ingredient_api_id) values ('almond milk', 93607);
insert into ingredients (name, ingredient_api_id) values ('banana', 9040);
insert into ingredients (name, ingredient_api_id) values ('chocolate protein powder', 99075);
insert into ingredients (name, ingredient_api_id) values ('pumpkin', 11422);
insert into ingredients (name, ingredient_api_id) values ('anchovies', 15001);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('crushed red pepper', 1032009);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('light tuna', 15184);
insert into ingredients (name, ingredient_api_id) values ('whole-wheat spaghetti', 10020124);
insert into ingredients (name, ingredient_api_id) values ('cherry tomatoes', 10311529);
insert into ingredients (name, ingredient_api_id) values ('dry yeast', 18375);
insert into ingredients (name, ingredient_api_id) values ('fennel seed', 2018);
insert into ingredients (name, ingredient_api_id) values ('feta cheese', 1019);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('ground flaxseed', 12220);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('mushrooms', 11260);
insert into ingredients (name, ingredient_api_id) values ('neufchatel cheese', 1031);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('canned cannellini beans', 10016051);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('oil cured black olives', 1039195);
insert into ingredients (name, ingredient_api_id) values ('pasta shells', 11020420);
insert into ingredients (name, ingredient_api_id) values ('pecorino romano cheese', 1038);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('tomatoes', 11529);
insert into ingredients (name, ingredient_api_id) values ('bay leaf', 2004);
insert into ingredients (name, ingredient_api_id) values ('butternut squash', 11485);
insert into ingredients (name, ingredient_api_id) values ('carrot', 11124);
insert into ingredients (name, ingredient_api_id) values ('celery', 11143);
insert into ingredients (name, ingredient_api_id) values ('fresh sage', 99226);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('green bell pepper', 11333);
insert into ingredients (name, ingredient_api_id) values ('italian seasoning', 1022027);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('leeks', 11246);
insert into ingredients (name, ingredient_api_id) values ('red bell pepper', 11821);
insert into ingredients (name, ingredient_api_id) values ('tomatoes', 11529);
insert into ingredients (name, ingredient_api_id) values ('zucchini', 11477);
insert into ingredients (name, ingredient_api_id) values ('canned white beans', 16051);
insert into ingredients (name, ingredient_api_id) values ('carrot', 11124);
insert into ingredients (name, ingredient_api_id) values ('chicken broth', 6194);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('italian turkey sausage', 7927);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('yellow onion', 10511282);
insert into ingredients (name, ingredient_api_id) values ('avocado', 9037);
insert into ingredients (name, ingredient_api_id) values ('lime juice', 9160);
insert into ingredients (name, ingredient_api_id) values ('multi grain bread', 18075);
insert into ingredients (name, ingredient_api_id) values ('parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('tomato', 11529);
insert into ingredients (name, ingredient_api_id) values ('chili powder', 2009);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('garlic clove', 11215);
insert into ingredients (name, ingredient_api_id) values ('kamut', 20138);
insert into ingredients (name, ingredient_api_id) values ('raw cashews', 12087);
insert into ingredients (name, ingredient_api_id) values ('sun-dried tomatoes', 11955);
insert into ingredients (name, ingredient_api_id) values ('tomato', 11529);
insert into ingredients (name, ingredient_api_id) values ('vegan cheese', 93701);
insert into ingredients (name, ingredient_api_id) values ('yeast', 18375);
insert into ingredients (name, ingredient_api_id) values ('crushed red pepper', 1032009);
insert into ingredients (name, ingredient_api_id) values ('frozen spinach', 11463);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('italian cheese blend', 93651);
insert into ingredients (name, ingredient_api_id) values ('low fat ricotta cheese', 1037);
insert into ingredients (name, ingredient_api_id) values ('marinara sauce', 10111549);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('red bell pepper', 11821);
insert into ingredients (name, ingredient_api_id) values ('red onion', 10011282);
insert into ingredients (name, ingredient_api_id) values ('whole wheat lasagna noodles', 10120124);
insert into ingredients (name, ingredient_api_id) values ('canned cannellini beans', 10016051);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('oil cured black olives', 1039195);
insert into ingredients (name, ingredient_api_id) values ('pasta shells', 11020420);
insert into ingredients (name, ingredient_api_id) values ('pecorino romano cheese', 1038);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('tomatoes', 11529);
insert into ingredients (name, ingredient_api_id) values ('canned cannellini beans', 10016051);
insert into ingredients (name, ingredient_api_id) values ('carrot', 11124);
insert into ingredients (name, ingredient_api_id) values ('celery stalks', 10111143);
insert into ingredients (name, ingredient_api_id) values ('chicken broth', 6194);
insert into ingredients (name, ingredient_api_id) values ('ham', 10151);
insert into ingredients (name, ingredient_api_id) values ('marinara sauce', 10111549);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('parmesan', 1033);
insert into ingredients (name, ingredient_api_id) values ('artichokes', 11007);
insert into ingredients (name, ingredient_api_id) values ('baby spinach', 11457);
insert into ingredients (name, ingredient_api_id) values ('basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('low fat cottage cheese', 1016);
insert into ingredients (name, ingredient_api_id) values ('Low Moisture Part-Skim Mozzarella Cheese', 1029);
insert into ingredients (name, ingredient_api_id) values ('packaged no-boil lasagna noodles', 10620420);
insert into ingredients (name, ingredient_api_id) values ('red onion', 10011282);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('asparagus', 11011);
insert into ingredients (name, ingredient_api_id) values ('fresh chives', 11156);
insert into ingredients (name, ingredient_api_id) values ('fresh tarragon', 2041);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('lemon zest', 9156);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('penne', 11120420);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('snap peas', 10011300);
insert into ingredients (name, ingredient_api_id) values ('broth', 1006615);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('dried basil', 2003);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('pasta', 20420);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('balsamic vinegar', 2069);
insert into ingredients (name, ingredient_api_id) values ('cooked rice', 10220445);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('roasted red peppers', 11916);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('avocado', 9037);
insert into ingredients (name, ingredient_api_id) values ('balsamic vinegar', 2069);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('fresh basil leaves', 2044);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('red onion', 10011282);
insert into ingredients (name, ingredient_api_id) values ('salmon filets', 15076);
insert into ingredients (name, ingredient_api_id) values ('vine ripened tomatoes', 11529);
insert into ingredients (name, ingredient_api_id) values ('fresh green beans', 11052);
insert into ingredients (name, ingredient_api_id) values ('grape tomatoes', 10111529);
insert into ingredients (name, ingredient_api_id) values ('lemon juice', 9152);
insert into ingredients (name, ingredient_api_id) values ('pesto', 93698);
insert into ingredients (name, ingredient_api_id) values ('salmon fillets', 15076);
insert into ingredients (name, ingredient_api_id) values ('baby spinach', 11457);
insert into ingredients (name, ingredient_api_id) values ('basil leaves', 2044);
insert into ingredients (name, ingredient_api_id) values ('granulated garlic', 1002020);
insert into ingredients (name, ingredient_api_id) values ('lasagna pasta', 10620420);
insert into ingredients (name, ingredient_api_id) values ('part-skim mozzarella', 1028);
insert into ingredients (name, ingredient_api_id) values ('part-skim ricotta cheese', 1037);
insert into ingredients (name, ingredient_api_id) values ('tomato sauce', 11549);
insert into ingredients (name, ingredient_api_id) values ('yellow bell pepper', 11951);
insert into ingredients (name, ingredient_api_id) values ('baby spinach leaves', 11457);
insert into ingredients (name, ingredient_api_id) values ('chicken stock', 6172);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('italian turkey sausage', 7927);
insert into ingredients (name, ingredient_api_id) values ('mozzarella cheese', 1026);
insert into ingredients (name, ingredient_api_id) values ('mushrooms', 11260);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('penne pasta', 11120420);
insert into ingredients (name, ingredient_api_id) values ('red onion', 10011282);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('baby spinach', 11457);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('red bell pepper', 11821);
insert into ingredients (name, ingredient_api_id) values ('yellow onion', 10511282);
insert into ingredients (name, ingredient_api_id) values ('zucchini', 11477);
insert into ingredients (name, ingredient_api_id) values ('butternut squash', 11485);
insert into ingredients (name, ingredient_api_id) values ('cranberries', 9078);
insert into ingredients (name, ingredient_api_id) values ('parmesan', 1033);
insert into ingredients (name, ingredient_api_id) values ('parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('pasta', 20420);
insert into ingredients (name, ingredient_api_id) values ('sage', 99226);
insert into ingredients (name, ingredient_api_id) values ('bay leaves', 2004);
insert into ingredients (name, ingredient_api_id) values ('butternut squash', 11485);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('ditalini pasta', 10020499);
insert into ingredients (name, ingredient_api_id) values ('fresh rosemary', 2063);
insert into ingredients (name, ingredient_api_id) values ('fresh thyme', 2049);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('red kidney beans', 16033);
insert into ingredients (name, ingredient_api_id) values ('vegetable broth', 6615);
insert into ingredients (name, ingredient_api_id) values ('yellow onion', 10511282);
insert into ingredients (name, ingredient_api_id) values ('yukon gold potatoes', 10211362);
insert into ingredients (name, ingredient_api_id) values ('zucchini', 11477);
insert into ingredients (name, ingredient_api_id) values ('butternut squash', 11485);
insert into ingredients (name, ingredient_api_id) values ('chives', 11156);
insert into ingredients (name, ingredient_api_id) values ('hazelnuts', 12120);
insert into ingredients (name, ingredient_api_id) values ('lemon zest', 9156);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('swiss chard', 11147);
insert into ingredients (name, ingredient_api_id) values ('yellow onions', 10511282);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('celery', 11143);
insert into ingredients (name, ingredient_api_id) values ('dried basil leaves', 2003);
insert into ingredients (name, ingredient_api_id) values ('dried pinto beans', 16042);
insert into ingredients (name, ingredient_api_id) values ('fresh rosemary', 2063);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('nutritional yeast', 93690);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('pasta', 20420);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('smoked paprika', 1012028);
insert into ingredients (name, ingredient_api_id) values ('banana', 9040);
insert into ingredients (name, ingredient_api_id) values ('chocolate protein powder', 99075);
insert into ingredients (name, ingredient_api_id) values ('cocoa powder', 19165);
insert into ingredients (name, ingredient_api_id) values ('cottage cheese', 1012);
insert into ingredients (name, ingredient_api_id) values ('vanilla', 2050);
insert into ingredients (name, ingredient_api_id) values ('basil leaves', 2044);
insert into ingredients (name, ingredient_api_id) values ('bay leaf', 2004);
insert into ingredients (name, ingredient_api_id) values ('bread', 18064);
insert into ingredients (name, ingredient_api_id) values ('canned white cannellini beans', 10016051);
insert into ingredients (name, ingredient_api_id) values ('celery stalks', 10111143);
insert into ingredients (name, ingredient_api_id) values ('fresh peas', 11304);
insert into ingredients (name, ingredient_api_id) values ('garlic clove', 11215);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('leeks', 11246);
insert into ingredients (name, ingredient_api_id) values ('lemon zest', 9156);
insert into ingredients (name, ingredient_api_id) values ('low sodium chicken stock', 1006970);
insert into ingredients (name, ingredient_api_id) values ('onions', 11282);
insert into ingredients (name, ingredient_api_id) values ('parmesan', 1033);
insert into ingredients (name, ingredient_api_id) values ('parsley leaves', 11297);
insert into ingredients (name, ingredient_api_id) values ('pistachios', 12151);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('sugar snap peas', 10011300);
insert into ingredients (name, ingredient_api_id) values ('thyme', 2049);
insert into ingredients (name, ingredient_api_id) values ('bread', 18064);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('egg', 1123);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('frozen spinach', 11463);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('lean ground beef', 23557);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('pecorino romano cheese', 1038);
insert into ingredients (name, ingredient_api_id) values ('canned chickpeas', 16058);
insert into ingredients (name, ingredient_api_id) values ('celery', 11143);
insert into ingredients (name, ingredient_api_id) values ('chard', 11147);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('leeks', 11246);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('peas', 11304);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('short pasta', 20499);
insert into ingredients (name, ingredient_api_id) values ('zucchini', 11477);
insert into ingredients (name, ingredient_api_id) values ('button mushrooms', 11260);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('italian herbs', 1022027);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('semolina', 20066);
insert into ingredients (name, ingredient_api_id) values ('tomatoes', 11529);
insert into ingredients (name, ingredient_api_id) values ('balsamic vinegar', 2069);
insert into ingredients (name, ingredient_api_id) values ('bread', 18064);
insert into ingredients (name, ingredient_api_id) values ('cauliflower', 11135);
insert into ingredients (name, ingredient_api_id) values ('chillies', 11819);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('oil-packed anchovies', 15002);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('risotto rice', 10020052);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('capers', 2054);
insert into ingredients (name, ingredient_api_id) values ('cauliflower', 11135);
insert into ingredients (name, ingredient_api_id) values ('flat-leaf parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('kalamata olives', 1009195);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('arborio rice', 10020052);
insert into ingredients (name, ingredient_api_id) values ('baby spinach', 11457);
insert into ingredients (name, ingredient_api_id) values ('chicken stock', 6172);
insert into ingredients (name, ingredient_api_id) values ('creamed corn', 11174);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('grated parmesan cheese', 1032);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('roast chicken', 5114);
insert into ingredients (name, ingredient_api_id) values ('black olives', 1059195);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('capers', 2054);
insert into ingredients (name, ingredient_api_id) values ('chilli', 11819);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('spaghetti', 11420420);
insert into ingredients (name, ingredient_api_id) values ('tomato puree', 11547);
insert into ingredients (name, ingredient_api_id) values ('tomatoes', 11529);
insert into ingredients (name, ingredient_api_id) values ('basil leaves', 2044);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('spaghetti', 11420420);
insert into ingredients (name, ingredient_api_id) values ('tomatoes', 11529);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('black olives', 1059195);
insert into ingredients (name, ingredient_api_id) values ('broccoli florets', 10011090);
insert into ingredients (name, ingredient_api_id) values ('carrot', 11124);
insert into ingredients (name, ingredient_api_id) values ('chicken stock', 6172);
insert into ingredients (name, ingredient_api_id) values ('corn starch', 20027);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('grape tomatoes', 10111529);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('orange bell pepper', 10011821);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('summer squash', 11641);
insert into ingredients (name, ingredient_api_id) values ('tri-color pasta', 12020420);
insert into ingredients (name, ingredient_api_id) values ('zucchini squash', 11477);
insert into ingredients (name, ingredient_api_id) values ('cooked brown rice', 20041);
insert into ingredients (name, ingredient_api_id) values ('mozzarella cheese', 1026);
insert into ingredients (name, ingredient_api_id) values ('pizza sauce', 11549);
insert into ingredients (name, ingredient_api_id) values ('red bell pepper', 11821);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('sweet onion', 11294);
insert into ingredients (name, ingredient_api_id) values ('turkey pepperoni', 7278);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('cooked chicken breast', 5064);
insert into ingredients (name, ingredient_api_id) values ('cooked pasta', 20421);
insert into ingredients (name, ingredient_api_id) values ('edamame', 11212);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('bay leaf', 2004);
insert into ingredients (name, ingredient_api_id) values ('butternut squash', 11485);
insert into ingredients (name, ingredient_api_id) values ('fontina cheese', 1020);
insert into ingredients (name, ingredient_api_id) values ('fresh sage', 99226);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('low fat milk', 1082);
insert into ingredients (name, ingredient_api_id) values ('nutmeg', 2025);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('packaged no-boil lasagna noodles', 10620420);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('thyme', 2049);
insert into ingredients (name, ingredient_api_id) values ('carrot', 11124);
insert into ingredients (name, ingredient_api_id) values ('cooked chicken breast', 5064);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('ginger', 11216);
insert into ingredients (name, ingredient_api_id) values ('green onion', 11291);
insert into ingredients (name, ingredient_api_id) values ('italian cheese blend', 93651);
insert into ingredients (name, ingredient_api_id) values ('peanut butter', 16098);
insert into ingredients (name, ingredient_api_id) values ('peanuts', 16091);
insert into ingredients (name, ingredient_api_id) values ('red bell pepper', 11821);
insert into ingredients (name, ingredient_api_id) values ('rice vinegar', 1022053);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('sugar-free apricot jam', 10543028);
insert into ingredients (name, ingredient_api_id) values ('tortilla', 18364);
insert into ingredients (name, ingredient_api_id) values ('seasoning', 1042027);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('great northern beans', 16025);
insert into ingredients (name, ingredient_api_id) values ('instant white rice', 20048);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('aubergine', 11209);
insert into ingredients (name, ingredient_api_id) values ('mushroom', 11260);
insert into ingredients (name, ingredient_api_id) values ('roasted red peppers', 11916);
insert into ingredients (name, ingredient_api_id) values ('passata', 10011547);
insert into ingredients (name, ingredient_api_id) values ('lasagne sheets', 10620420);
insert into ingredients (name, ingredient_api_id) values ('frozen spinach', 11463);
insert into ingredients (name, ingredient_api_id) values ('ricotta', 1036);
insert into ingredients (name, ingredient_api_id) values ('parmesan', 1033);
insert into ingredients (name, ingredient_api_id) values ('pine nut', 12147);
insert into ingredients (name, ingredient_api_id) values ('extra firm tofu', 16163);
insert into ingredients (name, ingredient_api_id) values ('frozen spinach', 11463);
insert into ingredients (name, ingredient_api_id) values ('garlic powder', 1022020);
insert into ingredients (name, ingredient_api_id) values ('italian seasoning', 1022027);
insert into ingredients (name, ingredient_api_id) values ('lemon juice', 9152);
insert into ingredients (name, ingredient_api_id) values ('marinara sauce', 10111549);
insert into ingredients (name, ingredient_api_id) values ('nutritional yeast', 93690);
insert into ingredients (name, ingredient_api_id) values ('parmesan', 1033);
insert into ingredients (name, ingredient_api_id) values ('whole wheat lasagna noodles', 10120124);
insert into ingredients (name, ingredient_api_id) values ('barley', 20004);
insert into ingredients (name, ingredient_api_id) values ('bay leaf', 2004);
insert into ingredients (name, ingredient_api_id) values ('chicken stock', 6172);
insert into ingredients (name, ingredient_api_id) values ('cremini mushrooms', 11266);
insert into ingredients (name, ingredient_api_id) values ('dried thyme', 2042);
insert into ingredients (name, ingredient_api_id) values ('dry white wine', 14106);
insert into ingredients (name, ingredient_api_id) values ('fennel bulb', 11957);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('pearl barley', 20005);
insert into ingredients (name, ingredient_api_id) values ('portabella mushroom caps', 11265);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('unsalted butter', 1145);
insert into ingredients (name, ingredient_api_id) values ('asparagus', 11011);
insert into ingredients (name, ingredient_api_id) values ('dried porcini mushrooms', 10011268);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('mushrooms', 11260);
insert into ingredients (name, ingredient_api_id) values ('quinoa', 20035);
insert into ingredients (name, ingredient_api_id) values ('shallot', 11677);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('vegetable broth', 6615);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('canned kidney beans', 16034);
insert into ingredients (name, ingredient_api_id) values ('carrot', 11124);
insert into ingredients (name, ingredient_api_id) values ('fresh basil leaves', 2044);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('ground flax seed', 12220);
insert into ingredients (name, ingredient_api_id) values ('oil packed sun dried tomatoes', 11956);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('rolled oats', 8120);
insert into ingredients (name, ingredient_api_id) values ('walnuts', 12155);
insert into ingredients (name, ingredient_api_id) values ('basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('cherry tomatoes', 10311529);
insert into ingredients (name, ingredient_api_id) values ('cremini mushrooms', 11266);
insert into ingredients (name, ingredient_api_id) values ('extra firm tofu', 16163);
insert into ingredients (name, ingredient_api_id) values ('fennel bulb', 11957);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('garlic clove', 11215);
insert into ingredients (name, ingredient_api_id) values ('juice of lemon', 9152);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('lasagna noodles', 10620420);
insert into ingredients (name, ingredient_api_id) values ('leek', 11246);
insert into ingredients (name, ingredient_api_id) values ('mozzarella cheese', 1026);
insert into ingredients (name, ingredient_api_id) values ('nutritional yeast', 93690);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('red onion', 10011282);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('zucchini', 11477);
insert into ingredients (name, ingredient_api_id) values ('chicken broth', 6194);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('garlic powder', 1022020);
insert into ingredients (name, ingredient_api_id) values ('half and half', 1049);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('mild cheddar', 1009);
insert into ingredients (name, ingredient_api_id) values ('red bell peppers', 11821);
insert into ingredients (name, ingredient_api_id) values ('red potatoes', 10011355);
insert into ingredients (name, ingredient_api_id) values ('yellow onion', 10511282);
insert into ingredients (name, ingredient_api_id) values ('canned great northern beans', 16026);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('croutons', 18242);
insert into ingredients (name, ingredient_api_id) values ('italian turkey sausage', 7927);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('reduced sodium chicken broth', 6970);
insert into ingredients (name, ingredient_api_id) values ('almonds', 12061);
insert into ingredients (name, ingredient_api_id) values ('baguette', 18033);
insert into ingredients (name, ingredient_api_id) values ('cayenne pepper', 2031);
insert into ingredients (name, ingredient_api_id) values ('fresh chives', 11156);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('fresh thyme', 2049);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('juice of lemon', 9152);
insert into ingredients (name, ingredient_api_id) values ('sour cream', 1056);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('almond milk', 93607);
insert into ingredients (name, ingredient_api_id) values ('basil leaves', 2044);
insert into ingredients (name, ingredient_api_id) values ('broccoli florets', 10011090);
insert into ingredients (name, ingredient_api_id) values ('carrot', 11124);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('grape tomatoes', 10111529);
insert into ingredients (name, ingredient_api_id) values ('hass avocados', 9037);
insert into ingredients (name, ingredient_api_id) values ('lemon juice', 9152);
insert into ingredients (name, ingredient_api_id) values ('penne pasta', 11120420);
insert into ingredients (name, ingredient_api_id) values ('raw cashews', 12087);
insert into ingredients (name, ingredient_api_id) values ('scallions', 11291);
insert into ingredients (name, ingredient_api_id) values ('zucchini', 11477);
insert into ingredients (name, ingredient_api_id) values ('apple', 9003);
insert into ingredients (name, ingredient_api_id) values ('baguette', 18033);
insert into ingredients (name, ingredient_api_id) values ('balsamic vinegar', 2069);
insert into ingredients (name, ingredient_api_id) values ('beets', 11080);
insert into ingredients (name, ingredient_api_id) values ('dijon mustard', 1002046);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('mozzarella', 1026);
insert into ingredients (name, ingredient_api_id) values ('sunflower seeds', 12036);
insert into ingredients (name, ingredient_api_id) values ('beef stock', 6170);
insert into ingredients (name, ingredient_api_id) values ('cajun seasoning', 1032028);
insert into ingredients (name, ingredient_api_id) values ('canned red kidney beans', 10016034);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('canned white cannellini beans', 10016051);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('celery', 11143);
insert into ingredients (name, ingredient_api_id) values ('collards', 11161);
insert into ingredients (name, ingredient_api_id) values ('ditalini pasta', 10020499);
insert into ingredients (name, ingredient_api_id) values ('dried basil', 2003);
insert into ingredients (name, ingredient_api_id) values ('dried sage', 2038);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('ground chuck', 10023572);
insert into ingredients (name, ingredient_api_id) values ('italian seasoning', 1022027);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('vegetable juice', 31008);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('cauliflower florets', 10011135);
insert into ingredients (name, ingredient_api_id) values ('egg', 1123);
insert into ingredients (name, ingredient_api_id) values ('flat leaf parsley leaves', 11297);
insert into ingredients (name, ingredient_api_id) values ('fresh basil leaves', 2044);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('parmesan', 1033);
insert into ingredients (name, ingredient_api_id) values ('part-skim mozzarella', 1028);
insert into ingredients (name, ingredient_api_id) values ('part-skim ricotta', 1037);
insert into ingredients (name, ingredient_api_id) values ('red bell pepper', 11821);
insert into ingredients (name, ingredient_api_id) values ('tomato paste', 11887);
insert into ingredients (name, ingredient_api_id) values ('whole-wheat lasagna noodles', 10120124);
insert into ingredients (name, ingredient_api_id) values ('cremini mushrooms', 11266);
insert into ingredients (name, ingredient_api_id) values ('shiitake mushrooms', 11238);
insert into ingredients (name, ingredient_api_id) values ('onions', 11282);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('tomato paste', 11887);
insert into ingredients (name, ingredient_api_id) values ('tomato sauce', 11549);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('dried thyme', 2042);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('frozen spinach', 11463);
insert into ingredients (name, ingredient_api_id) values ('lasagna noodles', 10620420);
insert into ingredients (name, ingredient_api_id) values ('ricotta cheese', 1036);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('pecorino cheese', 1038);
insert into ingredients (name, ingredient_api_id) values ('shredded mozzarella cheese', 1001026);
insert into ingredients (name, ingredient_api_id) values ('acorn squash', 11482);
insert into ingredients (name, ingredient_api_id) values ('fresh rosemary', 2063);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('pecans', 12142);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('turnip', 11564);
insert into ingredients (name, ingredient_api_id) values ('basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('marinara sauce', 10111549);
insert into ingredients (name, ingredient_api_id) values ('skim milk mozzarella cheese', 42304);
insert into ingredients (name, ingredient_api_id) values ('tomato', 11529);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('black olives', 1059195);
insert into ingredients (name, ingredient_api_id) values ('dry yeast', 18375);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('fresh herbs', 10111297);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('green olives', 1029195);
insert into ingredients (name, ingredient_api_id) values ('mozarella cheese', 1026);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('red wine', 14096);
insert into ingredients (name, ingredient_api_id) values ('tomato', 11529);
insert into ingredients (name, ingredient_api_id) values ('tomatoes', 11529);
insert into ingredients (name, ingredient_api_id) values ('basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('basil leaves', 2044);
insert into ingredients (name, ingredient_api_id) values ('courgettes', 11477);
insert into ingredients (name, ingredient_api_id) values ('dates', 9087);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('lemon juice', 9152);
insert into ingredients (name, ingredient_api_id) values ('lemon juice', 9152);
insert into ingredients (name, ingredient_api_id) values ('nutritional yeast', 93690);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('pine nuts', 12147);
insert into ingredients (name, ingredient_api_id) values ('pistachios', 12151);
insert into ingredients (name, ingredient_api_id) values ('raw cashews', 12087);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('sun-dried tomatoes', 11955);
insert into ingredients (name, ingredient_api_id) values ('tomato', 11529);
insert into ingredients (name, ingredient_api_id) values ('tomatoes', 11529);
insert into ingredients (name, ingredient_api_id) values ('basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('celery', 11143);
insert into ingredients (name, ingredient_api_id) values ('cheese', 1041009);
insert into ingredients (name, ingredient_api_id) values ('chicken base', 6080);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('green beans', 11052);
insert into ingredients (name, ingredient_api_id) values ('kidney beans', 16033);
insert into ingredients (name, ingredient_api_id) values ('mat beans', 99144);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('pasta', 20420);
insert into ingredients (name, ingredient_api_id) values ('tomato sauce', 11549);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('quinoa', 20035);
insert into ingredients (name, ingredient_api_id) values ('salmon', 15076);
insert into ingredients (name, ingredient_api_id) values ('vegetable stock', 6615);
insert into ingredients (name, ingredient_api_id) values ('fat-free ricotta cheese', 93630);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('goat cheese', 1159);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('lasagna noodles', 10620420);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('tomato puree', 11547);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('cashews', 12087);
insert into ingredients (name, ingredient_api_id) values ('crimini mushrooms', 11266);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('garlic granules', 1002020);
insert into ingredients (name, ingredient_api_id) values ('juice of lemon', 9152);
insert into ingredients (name, ingredient_api_id) values ('leek', 11246);
insert into ingredients (name, ingredient_api_id) values ('Miso Soybean Paste', 16112);
insert into ingredients (name, ingredient_api_id) values ('portobello mushrooms', 11265);
insert into ingredients (name, ingredient_api_id) values ('summer squash', 11641);
insert into ingredients (name, ingredient_api_id) values ('swiss chard', 11147);
insert into ingredients (name, ingredient_api_id) values ('zucchini', 11477);
insert into ingredients (name, ingredient_api_id) values ('baked chicken breasts', 5064);
insert into ingredients (name, ingredient_api_id) values ('garlic powder', 1022020);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('part skim ricotta', 1037);
insert into ingredients (name, ingredient_api_id) values ('tomato paste', 11887);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('leeks', 11246);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('pearl barley', 20005);
insert into ingredients (name, ingredient_api_id) values ('vegetable broth', 6615);
insert into ingredients (name, ingredient_api_id) values ('white mushrooms', 11260);
insert into ingredients (name, ingredient_api_id) values ('white wine', 14106);
insert into ingredients (name, ingredient_api_id) values ('bell peppers', 10211821);
insert into ingredients (name, ingredient_api_id) values ('pizza sauce', 11549);
insert into ingredients (name, ingredient_api_id) values ('shredded mozzarella cheese', 1001026);
insert into ingredients (name, ingredient_api_id) values ('whole wheat rolls', 18351);
insert into ingredients (name, ingredient_api_id) values ('bay leaf', 2004);
insert into ingredients (name, ingredient_api_id) values ('canned cannellini beans', 10016051);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('celery', 11143);
insert into ingredients (name, ingredient_api_id) values ('chicken stock', 6172);
insert into ingredients (name, ingredient_api_id) values ('ditalini pasta', 10020499);
insert into ingredients (name, ingredient_api_id) values ('fennel seeds', 2018);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('italian sausage', 7036);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('parmesan', 1033);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('tomato paste', 11887);
insert into ingredients (name, ingredient_api_id) values ('white wine', 14106);
insert into ingredients (name, ingredient_api_id) values ('capers', 2054);
insert into ingredients (name, ingredient_api_id) values ('crushed red pepper', 1032009);
insert into ingredients (name, ingredient_api_id) values ('eggplant', 11209);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('green olives', 1029195);
insert into ingredients (name, ingredient_api_id) values ('plum tomatoes', 10411529);
insert into ingredients (name, ingredient_api_id) values ('red wine vinegar', 1022068);
insert into ingredients (name, ingredient_api_id) values ('whole-wheat angel hair pasta', 10420124);
insert into ingredients (name, ingredient_api_id) values ('baby spinach', 11457);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('frozen artichoke hearts', 11009);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('lemon zest', 9156);
insert into ingredients (name, ingredient_api_id) values ('lobster', 15147);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('pearl barley', 20005);
insert into ingredients (name, ingredient_api_id) values ('pecorino romano cheese', 1038);
insert into ingredients (name, ingredient_api_id) values ('shrimp', 15152);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('canned white beans', 16051);
insert into ingredients (name, ingredient_api_id) values ('crushed red pepper', 1032009);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('frozen spinach', 11463);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('gnocchi', 98853);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('part skim mozzarella cheese', 1028);
insert into ingredients (name, ingredient_api_id) values ('balsamic vinegar', 2069);
insert into ingredients (name, ingredient_api_id) values ('capers', 2054);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('swiss chard', 11147);
insert into ingredients (name, ingredient_api_id) values ('bacon', 10123);
insert into ingredients (name, ingredient_api_id) values ('baguette', 18033);
insert into ingredients (name, ingredient_api_id) values ('bay leaf', 2004);
insert into ingredients (name, ingredient_api_id) values ('butternut squash', 11485);
insert into ingredients (name, ingredient_api_id) values ('canned cannellini beans', 10016051);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('celery', 11143);
insert into ingredients (name, ingredient_api_id) values ('chicken stock', 6172);
insert into ingredients (name, ingredient_api_id) values ('dried thyme', 2042);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('pasta', 20420);
insert into ingredients (name, ingredient_api_id) values ('yellow onion', 10511282);
insert into ingredients (name, ingredient_api_id) values ('black olives', 1059195);
insert into ingredients (name, ingredient_api_id) values ('breadcrumbs', 18079);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('rigatoni pasta', 11220420);
insert into ingredients (name, ingredient_api_id) values ('soy sausage', 98971);
insert into ingredients (name, ingredient_api_id) values ('tomato sauce', 11549);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('soy cheese', 93701);
insert into ingredients (name, ingredient_api_id) values ('tomato sauce', 11549);
insert into ingredients (name, ingredient_api_id) values ('capers', 2054);
insert into ingredients (name, ingredient_api_id) values ('cherry tomatoes', 10311529);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('garlic clove', 11215);
insert into ingredients (name, ingredient_api_id) values ('oil cured black olives', 1039195);
insert into ingredients (name, ingredient_api_id) values ('oil packed tuna', 15119);
insert into ingredients (name, ingredient_api_id) values ('pine nuts', 12147);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('ricotta', 1036);
insert into ingredients (name, ingredient_api_id) values ('shiitake mushrooms', 11238);
insert into ingredients (name, ingredient_api_id) values ('spaghetti squash', 11492);
insert into ingredients (name, ingredient_api_id) values ('almond milk', 93607);
insert into ingredients (name, ingredient_api_id) values ('cauliflower', 11135);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('lemon juice', 9152);
insert into ingredients (name, ingredient_api_id) values ('nutritional yeast', 93690);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('zucchinis', 11477);
insert into ingredients (name, ingredient_api_id) values ('dried basil', 2003);
insert into ingredients (name, ingredient_api_id) values ('extra firm tofu', 16163);
insert into ingredients (name, ingredient_api_id) values ('frozen spinach', 11463);
insert into ingredients (name, ingredient_api_id) values ('hummus', 16158);
insert into ingredients (name, ingredient_api_id) values ('garlic powder', 1022020);
insert into ingredients (name, ingredient_api_id) values ('marinara sauce', 10111549);
insert into ingredients (name, ingredient_api_id) values ('nutritional yeast', 93690);
insert into ingredients (name, ingredient_api_id) values ('whole wheat lasagna noodles', 10120124);
insert into ingredients (name, ingredient_api_id) values ('chicken broth', 6194);
insert into ingredients (name, ingredient_api_id) values ('italian turkey sausage', 7927);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('parmesan', 1033);
insert into ingredients (name, ingredient_api_id) values ('penne pasta', 11120420);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('cooked lasagna noodles', 10620421);
insert into ingredients (name, ingredient_api_id) values ('crushed red pepper', 1032009);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('frozen spinach', 11463);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('green bell peppers', 11333);
insert into ingredients (name, ingredient_api_id) values ('mozzarella', 1026);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('parmesan', 1033);
insert into ingredients (name, ingredient_api_id) values ('red bell peppers', 11821);
insert into ingredients (name, ingredient_api_id) values ('red wine vinegar', 1022068);
insert into ingredients (name, ingredient_api_id) values ('ricotta', 1036);
insert into ingredients (name, ingredient_api_id) values ('roasted red bell peppers', 11916);
insert into ingredients (name, ingredient_api_id) values ('yellow squash', 11641);
insert into ingredients (name, ingredient_api_id) values ('zucchini', 11477);
insert into ingredients (name, ingredient_api_id) values ('almond milk', 93607);
insert into ingredients (name, ingredient_api_id) values ('butternut squash', 11485);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('herbs', 1002044);
insert into ingredients (name, ingredient_api_id) values ('lemon zest', 9156);
insert into ingredients (name, ingredient_api_id) values ('mozzarella', 1026);
insert into ingredients (name, ingredient_api_id) values ('nutritional yeast', 93690);
insert into ingredients (name, ingredient_api_id) values ('onions', 11282);
insert into ingredients (name, ingredient_api_id) values ('pine nuts', 12147);
insert into ingredients (name, ingredient_api_id) values ('raw cashews', 12087);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('tomatoes', 11529);
insert into ingredients (name, ingredient_api_id) values ('zucchini', 11477);
insert into ingredients (name, ingredient_api_id) values ('butternut squash', 11485);
insert into ingredients (name, ingredient_api_id) values ('fresh sage', 99226);
insert into ingredients (name, ingredient_api_id) values ('frozen spinach', 11463);
insert into ingredients (name, ingredient_api_id) values ('garlic clove', 11215);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('ricotta', 1036);
insert into ingredients (name, ingredient_api_id) values ('shallot', 11677);
insert into ingredients (name, ingredient_api_id) values ('shredded chicken', 1005114);
insert into ingredients (name, ingredient_api_id) values ('whole wheat lasagna noodles', 10120124);
insert into ingredients (name, ingredient_api_id) values ('dried yeast', 18375);
insert into ingredients (name, ingredient_api_id) values ('honey', 19296);
insert into ingredients (name, ingredient_api_id) values ('pizza sauce', 11549);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('risotto rice', 10020052);
insert into ingredients (name, ingredient_api_id) values ('asparagus', 11011);
insert into ingredients (name, ingredient_api_id) values ('vegetable stock', 6615);
insert into ingredients (name, ingredient_api_id) values ('parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('asparagus', 11011);
insert into ingredients (name, ingredient_api_id) values ('cherry tomatoes', 10311529);
insert into ingredients (name, ingredient_api_id) values ('parmesan', 1033);
insert into ingredients (name, ingredient_api_id) values ('cooked whole wheat pasta', 20125);
insert into ingredients (name, ingredient_api_id) values ('milk', 1077);
insert into ingredients (name, ingredient_api_id) values ('nutmeg', 2025);
insert into ingredients (name, ingredient_api_id) values ('nutritional yeast', 93690);
insert into ingredients (name, ingredient_api_id) values ('silken tofu', 16161);
insert into ingredients (name, ingredient_api_id) values ('butternut squash', 11485);
insert into ingredients (name, ingredient_api_id) values ('cranberries', 9078);
insert into ingredients (name, ingredient_api_id) values ('multi grain bread', 18075);
insert into ingredients (name, ingredient_api_id) values ('pumpkin pie spice', 1002035);
insert into ingredients (name, ingredient_api_id) values ('walnuts', 12155);
insert into ingredients (name, ingredient_api_id) values ('white balsamic vinegar', 1012069);
insert into ingredients (name, ingredient_api_id) values ('white onion', 10611282);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('pizza dough', 93610);
insert into ingredients (name, ingredient_api_id) values ('baby spinach', 11457);
insert into ingredients (name, ingredient_api_id) values ('canned black beans', 16018);
insert into ingredients (name, ingredient_api_id) values ('canned great northern beans', 16026);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('celery', 11143);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('fresh green beans', 11052);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('fresh thyme', 2049);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('spaghetti', 11420420);
insert into ingredients (name, ingredient_api_id) values ('tomatoes', 11529);
insert into ingredients (name, ingredient_api_id) values ('vegetable broth', 6615);
insert into ingredients (name, ingredient_api_id) values ('zucchini', 11477);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('low sodium chicken broth', 6970);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('parmesan', 1033);
insert into ingredients (name, ingredient_api_id) values ('penne', 11120420);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('shredded mozzarella', 1001026);
insert into ingredients (name, ingredient_api_id) values ('skinless boneless chicken breasts', 1055062);
insert into ingredients (name, ingredient_api_id) values ('tomato paste', 11887);
insert into ingredients (name, ingredient_api_id) values ('bell pepper', 10211821);
insert into ingredients (name, ingredient_api_id) values ('chicken stock', 6172);
insert into ingredients (name, ingredient_api_id) values ('farro', 10020005);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('mushrooms', 11260);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('canned red kidney beans', 10016034);
insert into ingredients (name, ingredient_api_id) values ('canned white kidney beans', 10116034);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('fire roasted tomatoes', 98849);
insert into ingredients (name, ingredient_api_id) values ('frozen corn', 11913);
insert into ingredients (name, ingredient_api_id) values ('garlic cloves', 11215);
insert into ingredients (name, ingredient_api_id) values ('green cabbage', 11109);
insert into ingredients (name, ingredient_api_id) values ('onion', 11282);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('parmesan cheese', 1033);
insert into ingredients (name, ingredient_api_id) values ('red pepper flakes', 1032009);
insert into ingredients (name, ingredient_api_id) values ('spinach', 10011457);
insert into ingredients (name, ingredient_api_id) values ('squash', 10011485);
insert into ingredients (name, ingredient_api_id) values ('thyme', 2049);
insert into ingredients (name, ingredient_api_id) values ('vegetable stock', 6615);
insert into ingredients (name, ingredient_api_id) values ('whole wheat pasta shells', 10320124);
insert into ingredients (name, ingredient_api_id) values ('zucchini', 11477);
insert into ingredients (name, ingredient_api_id) values ('asparagus', 11011);
insert into ingredients (name, ingredient_api_id) values ('bay leaves', 2004);
insert into ingredients (name, ingredient_api_id) values ('canned tomatoes', 10011693);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('italian seasoning', 1022027);
insert into ingredients (name, ingredient_api_id) values ('kale', 11233);
insert into ingredients (name, ingredient_api_id) values ('nutritional yeast', 93690);
insert into ingredients (name, ingredient_api_id) values ('peas', 11304);
insert into ingredients (name, ingredient_api_id) values ('quinoa', 20035);
insert into ingredients (name, ingredient_api_id) values ('white onion', 10611282);
insert into ingredients (name, ingredient_api_id) values ('zucchini', 11477);
insert into ingredients (name, ingredient_api_id) values ('bay leaves', 2004);
insert into ingredients (name, ingredient_api_id) values ('canned diced tomatoes', 11531);
insert into ingredients (name, ingredient_api_id) values ('carrots', 11124);
insert into ingredients (name, ingredient_api_id) values ('celery', 11143);
insert into ingredients (name, ingredient_api_id) values ('cremini mushroom', 11266);
insert into ingredients (name, ingredient_api_id) values ('dried marjoram', 2023);
insert into ingredients (name, ingredient_api_id) values ('dried rosemary', 2036);
insert into ingredients (name, ingredient_api_id) values ('dried thyme', 2042);
insert into ingredients (name, ingredient_api_id) values ('fresh basil', 2044);
insert into ingredients (name, ingredient_api_id) values ('fresh parsley', 11297);
insert into ingredients (name, ingredient_api_id) values ('garlic', 11215);
insert into ingredients (name, ingredient_api_id) values ('low sodium beef broth', 10093741);
insert into ingredients (name, ingredient_api_id) values ('oregano', 2027);
insert into ingredients (name, ingredient_api_id) values ('red wine vinegar', 1022068);
insert into ingredients (name, ingredient_api_id) values ('rump roast', 23618);
insert into ingredients (name, ingredient_api_id) values ('russet potatoes', 11353);
insert into ingredients (name, ingredient_api_id) values ('yellow onion', 10511282);
