insert into recipes (name, recipe_api_id) values ('Sweet Potato Kale Pizza with Rosemary & Red Onion', 548450);
insert into recipes (name, recipe_api_id) values ('creamy parmesan garlic gnocchi', 613283);
insert into recipes (name, recipe_api_id) values ('Pasta e Fagioli', 246727);
insert into recipes (name, recipe_api_id) values ('Inside-Out Lasagna', 695172);
insert into recipes (name, recipe_api_id) values ('One-Pot Pasta Primavera', 758622);
insert into recipes (name, recipe_api_id) values ('Pumpkin Pie Oatmeal', 611822);
insert into recipes (name, recipe_api_id) values ('Fusilli with Italian Sausage & Arugula', 694949);
insert into recipes (name, recipe_api_id) values ('sweet potato (vegan) alfredo', 446450);
insert into recipes (name, recipe_api_id) values ('Springtime Crockpot Minestrone', 525578);
insert into recipes (name, recipe_api_id) values ('Chocolate Pumpkin Banana Smoothie', 573041);
insert into recipes (name, recipe_api_id) values ('Tuna Pomodoro', 696739);
insert into recipes (name, recipe_api_id) values ('Deep-Dish Skillet Pizza', 759293);
insert into recipes (name, recipe_api_id) values ('Fresh Pomodoro Pasta, White Beans & Olives', 695600);
insert into recipes (name, recipe_api_id) values ('Fall Minestrone Soup', 508233);
insert into recipes (name, recipe_api_id) values ('White Bean Soup with Kale and Turkey Italian Sausage', 497270);
insert into recipes (name, recipe_api_id) values ('Easy Breakfast Bruschetta with Tomato and Avocado – Nigella Lawson – 50 Women Game Changers In Food', 474360);
insert into recipes (name, recipe_api_id) values ('Homemade Vegan Calzones with Sun-Dried Tomato & Pesto Spread', 735809);
insert into recipes (name, recipe_api_id) values ('Lasagna Rolls with a Pomodoro Sauce', 516621);
insert into recipes (name, recipe_api_id) values ('Pomodoro Pasta with White Beans & Olives', 697245);
insert into recipes (name, recipe_api_id) values ('Hearty Tortellini Pasta e Fagioli', 198272);
insert into recipes (name, recipe_api_id) values ('Spinach Artichoke Lasagna', 688040);
insert into recipes (name, recipe_api_id) values ('Pasta Primavera with Peas, Asparagus and Kale', 749120);
insert into recipes (name, recipe_api_id) values ('Italian Noodle Soup', 592686);
insert into recipes (name, recipe_api_id) values ('Italian Rice', 443063);
insert into recipes (name, recipe_api_id) values ('Grilled Salmon with Avocado Bruschetta', 996436);
insert into recipes (name, recipe_api_id) values ('Pesto Salmon and Italian Veggies in Foil', 959299);
insert into recipes (name, recipe_api_id) values ('Spinach Ricotta Lasagna in a Mug', 828936);
insert into recipes (name, recipe_api_id) values ('Penne Pasta with Spicy Italian Sausage, Mushrooms, and Spinach', 621272);
insert into recipes (name, recipe_api_id) values ('Best Vegetable Lasagna', 954350);
insert into recipes (name, recipe_api_id) values ('butternut squash pasta salad', 591173);
insert into recipes (name, recipe_api_id) values ('Autumn Minestrone Soup', 678499);
insert into recipes (name, recipe_api_id) values ('Hazelnut & Chard Ravioli Salad Recipe', 20067);
insert into recipes (name, recipe_api_id) values ('Pasta Fagioli with Cranberry Beans and Kale', 620122);
insert into recipes (name, recipe_api_id) values ('Chocolate Banana Protein Smoothie', 709339);
insert into recipes (name, recipe_api_id) values ('Spring Minestrone Verde with Pistachio Pesto', 736024);
insert into recipes (name, recipe_api_id) values ('Skinny Italian Spinach Meatballs', 19709);
insert into recipes (name, recipe_api_id) values ('Green Vegetable Minestrone', 695416);
insert into recipes (name, recipe_api_id) values ('mushroom spaghetti bolognese , veg mushroom spaghetti bolognese', 486817);
insert into recipes (name, recipe_api_id) values ('Cauliflower Risotto Recipe (risotto Ai Cavolfiori)', 30687);
insert into recipes (name, recipe_api_id) values ('Cauliflower in Puttanesca Sauce', 616091);
insert into recipes (name, recipe_api_id) values (' Baked Chicken & Corn Risotto', 494262);
insert into recipes (name, recipe_api_id) values ('Spaghetti alla puttanesca', 578104);
insert into recipes (name, recipe_api_id) values ('Spaghetti Pomodoro With Grilled Tempeh', 26902);
insert into recipes (name, recipe_api_id) values ('Pasta Primavera', 595401);
insert into recipes (name, recipe_api_id) values ('Pepperoni Pizza Rice', 506334);
insert into recipes (name, recipe_api_id) values ('Pasta Primavera', 77001);
insert into recipes (name, recipe_api_id) values ('Butternut Squash, Caramelized Onion, and Spinach Lasagna', 209205);
insert into recipes (name, recipe_api_id) values ('Thai Chicken Pizza', 558606);
insert into recipes (name, recipe_api_id) values ('Italian Style Rice And Beans', 52256);
insert into recipes (name, recipe_api_id) values ('Five-veg lasagne', 223743);
insert into recipes (name, recipe_api_id) values ('Lasagna Rolls', 262957);
insert into recipes (name, recipe_api_id) values ('Barley Risotto with Mushrooms and Spinach', 617062);
insert into recipes (name, recipe_api_id) values ('Porcini Mushroom Quinoa Risotto', 505049);
insert into recipes (name, recipe_api_id) values ('Italian Bean Balls and Spaghetti Squash Noodles', 262710);
insert into recipes (name, recipe_api_id) values ('Roasted Vegetable Lasagna', 998351);
insert into recipes (name, recipe_api_id) values ('Italian Sausage and Kale Soup', 537611);
insert into recipes (name, recipe_api_id) values ('Italian Sausage Stew with White Beans and Kale', 729352);
insert into recipes (name, recipe_api_id) values ('Spinach Almond Crostini', 771975);
insert into recipes (name, recipe_api_id) values ('Creamy Vegan Pasta Primavera', 250991);
insert into recipes (name, recipe_api_id) values ('Roasted Beet and Kale Panzanella', 496919);
insert into recipes (name, recipe_api_id) values ('Pasta e Fagioli Soup', 243663);
insert into recipes (name, recipe_api_id) values ('Roasted Cauliflower Lasagna', 752413);
insert into recipes (name, recipe_api_id) values ('Vegetarian Spinach and Mushroom Lasagna', 245768);
insert into recipes (name, recipe_api_id) values ('Turnip and Spinach Rosemary “Risotto” Stuffed Acorn Squash with Pecans', 619678);
insert into recipes (name, recipe_api_id) values ('Grilled Caprese Pizza', 594351);
insert into recipes (name, recipe_api_id) values ('veg pizza , how to make vegetable pizza', 487394);
insert into recipes (name, recipe_api_id) values ('The Best Raw Lasagna', 602979);
insert into recipes (name, recipe_api_id) values ('Pasta e Fagioli', 591620);
insert into recipes (name, recipe_api_id) values ('Quinoa Risotto With Salmon And Kale', 15276);
insert into recipes (name, recipe_api_id) values ('Kale Lasagna Diavolo', 758660);
insert into recipes (name, recipe_api_id) values ('Vegetable Lasagna With Cashew Cheese', 20376);
insert into recipes (name, recipe_api_id) values ('Naked Chicken Parmesan', 521509);
insert into recipes (name, recipe_api_id) values ('Mushroom Barley Risotto', 830830);
insert into recipes (name, recipe_api_id) values ('Pizza Sliders', 514635);
insert into recipes (name, recipe_api_id) values ('Pasta e Fagioli Soup (Italian Pasta and Bean Soup)', 248876);
insert into recipes (name, recipe_api_id) values ('Eggplant Pomodoro Pasta', 695547);
insert into recipes (name, recipe_api_id) values ('Slow Cooker Shrimp and Artichoke Barley Risotto', 573321);
insert into recipes (name, recipe_api_id) values ('A Warming Winter Dinner: Skillet Gnocchi with Spinach and White Beans', 516775);
insert into recipes (name, recipe_api_id) values ('Italian Style Swiss Chard', 101643);
insert into recipes (name, recipe_api_id) values ('Minestrone Soup with Butternut Squash, Kale and White Beans {How We Eat on a Budget}', 487780);
insert into recipes (name, recipe_api_id) values ('Rigatoni Puttanesca with Veggie Meatballs', 758976);
insert into recipes (name, recipe_api_id) values ('Polenta ‘Pizza’ with Kale Topping', 762009);
insert into recipes (name, recipe_api_id) values ('Sheet-Pan Spaghetti Squash Puttanesca', 677809);
insert into recipes (name, recipe_api_id) values ('Alfredo Zucchini Pasta', 496203);
insert into recipes (name, recipe_api_id) values ('Skinny Vegan Lasagna', 584303);
insert into recipes (name, recipe_api_id) values ('{38 Power Foods} Weight Watchers Pasta with Italian Chicken Sausage and Kale', 525490);
insert into recipes (name, recipe_api_id) values ('Roasted Vegetable Lasagna with Roasted Red Pepper Sauce', 508369);
insert into recipes (name, recipe_api_id) values ('Butternut Squash Lasagna With Zucchini Noodles (Vegan & Gluten-Free)', 627791);
insert into recipes (name, recipe_api_id) values ('Butternut squash lasagna roll ups with chicken and spinach', 616388);
insert into recipes (name, recipe_api_id) values ('Stove Top Pizza', 667188);
insert into recipes (name, recipe_api_id) values ('Baked asparagus risotto', 212657);
insert into recipes (name, recipe_api_id) values ('Instant Vegan Alfredo', 262959);
insert into recipes (name, recipe_api_id) values ('Fall Harvest Panzanella #SundaySupper', 612786);
insert into recipes (name, recipe_api_id) values ('Garlicky Kale and Ricotta Pizza', 1003938);
insert into recipes (name, recipe_api_id) values ('Vegetable Garden Minestrone Soup', 531452);
insert into recipes (name, recipe_api_id) values ('Chicken Parm Soup', 775913);
insert into recipes (name, recipe_api_id) values ('Farro Risotto: Wholesome Whole Grain', 578414);
insert into recipes (name, recipe_api_id) values ('Hearty Minestrone Soup #MysteryDish', 610252);
insert into recipes (name, recipe_api_id) values ('Spring Vegetable Quinoa Minestrone', 730835);
insert into recipes (name, recipe_api_id) values ('Italian Beef Stew', 543872);
